spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://server2:7310/eureka/
  instance:
    hostname: server1
server:
  port: 7306