server:
  port: 7308
spring:
  application:
    name: eureka-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7306/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true