spring:
  application:
    name: eureka-server
server:
  port: 7306
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultzone: http://loacalhost:7306/eureka/
  instance:
    hostname: localhost
